# Generated by Django 6.0.7 on 2026-08-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-clock_in']},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_working_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
