# Generated by Django 6.0.7 on 2026-08-28 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('fms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_image', models.ImageField(upload_to='registered_faces/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registered_face', to='fms.employeeprofile')),
            ],
        ),
    ]
