# Generated by Django 6.0.7 on 2026-08-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_registeredface'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
